spring.application.name=lab7_673380391_3_sec3

spring.datasource.url=jdbc:postgresql://localhost:5432/lab7
spring.datasource.username=postgres
spring.datasource.password=032599

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
